package com.vision.common.interfaces.service_notifications_manager;


import com.vision.common.interfaces.service_notification_sender.ServiceNotificationSender;
import com.vision.common.interfaces.service_notifications_executor.ServiceNotificationsExecutor;

public interface ServiceNotificationsManager extends ServiceNotificationSender, ServiceNotificationsExecutor {
}
